// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFl45ch2qYS5IbR8eMUWps33gdMVv07U',
    appId: '1:306969401241:web:605af745cef9261fec6508',
    messagingSenderId: '306969401241',
    projectId: 'check-check-app-30723',
    authDomain: 'check-check-app-30723.firebaseapp.com',
    storageBucket: 'check-check-app-30723.appspot.com',
    measurementId: 'G-BKWKT2G7GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuphxemShQOoQz7ZcZlSWVYtJhZa8oyU',
    appId: '1:306969401241:android:4dabedf0918f01b3ec6508',
    messagingSenderId: '306969401241',
    projectId: 'check-check-app-30723',
    storageBucket: 'check-check-app-30723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQu_LiD7FuY-qgr1MvK9TuYvVuVAoKFHw',
    appId: '1:306969401241:ios:a1e4805a8006a798ec6508',
    messagingSenderId: '306969401241',
    projectId: 'check-check-app-30723',
    storageBucket: 'check-check-app-30723.appspot.com',
    iosBundleId: 'com.example.checkCheckApp',
  );
}
